#!/usr/bin/env python3
"""Generate Python gRPC stubs from proto/engine.proto.

Usage:
    python scripts/gen_proto_python.py

Output: python/engine/proto/ (engine_pb2.py + engine_pb2_grpc.py)
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
PROTO_FILE = ROOT / "proto" / "engine.proto"
PROTO_DIR = ROOT / "proto"
OUT_DIR = ROOT / "python" / "engine" / "proto"


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    cmd = [
        sys.executable, "-m", "grpc_tools.protoc",
        f"--proto_path={PROTO_DIR}",
        f"--python_out={OUT_DIR}",
        f"--grpc_python_out={OUT_DIR}",
        str(PROTO_FILE),
    ]
    print("Running:", " ".join(cmd))
    result = subprocess.run(cmd, check=False)
    if result.returncode != 0:
        print("ERROR: protoc failed. Install grpcio-tools: uv pip install grpcio-tools")
        sys.exit(result.returncode)

    # Write __init__.py so the directory is a package.
    init = OUT_DIR / "__init__.py"
    if not init.exists():
        init.write_text("# Generated by scripts/gen_proto_python.py - do not edit.\n")

    # Fix grpc stub import: grpc_tools generates `import engine_pb2` (top-level),
    # but the stubs live in the engine.proto package, so patch to a relative import.
    grpc_file = OUT_DIR / "engine_pb2_grpc.py"
    if grpc_file.exists():
        text = grpc_file.read_text(encoding="utf-8")
        patched = text.replace(
            "import engine_pb2 as engine__pb2",
            "from engine.proto import engine_pb2 as engine__pb2",
        )
        if patched != text:
            grpc_file.write_text(patched, encoding="utf-8")
            print("Patched engine_pb2_grpc.py import path.")

    print(f"Generated stubs in {OUT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
